### ISSUE TITLE
[HW] Saverio Guzzo

### ISSUE THREAD

**Issue by saveriogzz** [datastaxdevs/event-streaming-series#9]
Name: Saverio Guzzo
email: saverio.g.guzzo@gmail.com
linkedin: [saverioguzzo](https://www.linkedin.com/in/saverioguzzo/)

![scenario6](https://user-images.githubusercontent.com/42075938/123133555-29482c00-d450-11eb-90c5-051c81101fc8.png)
![scenario5](https://user-images.githubusercontent.com/42075938/123133558-29e0c280-d450-11eb-82f5-2c2821d14727.png)
![scenario4](https://user-images.githubusercontent.com/42075938/123133560-2a795900-d450-11eb-9c22-a56ddce8d577.png)
![scenario3](https://user-images.githubusercontent.com/42075938/123133564-2a795900-d450-11eb-8ffe-2b123acd94f0.png)
![scenario2](https://user-images.githubusercontent.com/42075938/123133566-2b11ef80-d450-11eb-8472-d40f77b6cb86.png)
![scenario1](https://user-images.githubusercontent.com/42075938/123133567-2b11ef80-d450-11eb-89d5-40de0987bb8a.png)

**Comment by SonicDMG** [comment]
Well done Saverio. Here's your badge -> https://api.badgr.io/public/assertions/NBSWC-RNTOK3TJTTNpSfXg?identity__email=saverio.g.guzzo%40gmail.com

**Comment by saveriogzz** [comment]
Thanks David!! I'm gonna close this, cheers
